[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "tradesystem"
version = "0.1.0"
description = "A trading system for Polymarket and binance with backtest functionality"